---
- name: export aws public dns
  shell: curl -s http://169.254.169.254/latest/meta-data/public-hostname
  register: aws_public_dns

- name: install nginx
  apt: name=nginx state=present update_cache=yes
  notify: restart nginx
 
- name: set index.html
  template:
    src: index.html.j2
    dest: /usr/share/nginx/html/index.html
  notify: restart nginx
 
- debug: msg="Pleas try access your webserver through http://{{ aws_public_dns.stdout }}/"